---

- name: Ensure snapd is installed
  become: yes
  dnf:
    name: snapd
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Ensure snapd is installed
  become: yes
  apt:
    name: snapd
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Enable snapd service
  become: yes
  service:
    name: snapd
    state: started
    enabled: yes
  when: ansible_facts["distribution"] == "Fedora" or ansible_facts["distribution"] == "Ubuntu"
