---

- hosts: localhost
  vars:
    is_fedora: yes
  roles:
    - yum_compat
    - desktop
    - development_workstation
  tasks:
    - include_tasks: tasks/fedora/system.yml
    - include_tasks: tasks/fedora/docker.yml
