---
- hosts: localhost
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - include_tasks: tasks/ubuntu/system.yml
    - include_tasks: tasks/ubuntu/development.yml
    - include_tasks: tasks/ubuntu/docker.yml
    - include_tasks: tasks/ubuntu/desktop.yml
    - include_tasks: tasks/dotfiles.yml
