---

- name: Add Keybase repo
  become: yes
  yum_repository:
    name: keybase
    description: Keybase
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
  when: is_rhel or is_fedora

- name: Add Keybase repo
  apt_repository:
    repo: deb http://prerelease.keybase.io/deb stable main
    state: present
    filename: keybase
  when: is_ubuntu

- name: Install Keybase
  become: yes
  dnf:
    name: keybase
    state: present
  when: is_fedora

- name: Install Keybase
  become: yes
  yum:
    name: keybase
    state: present
  when: is_rhel

- name: Install Keybase
  become: yes
  apt:
    name: keybase
    state: present
  when: is_ubuntu
