---

- name: Add Keybase repo
  become: yes
  yum_repository:
    name: keybase
    description: Keybase
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
  when: is_rhel or is_fedora

- name: Install Keybase
  become: yes
  dnf:
    name: keybase
    state: present
  when: is_fedora

- name: Install Keybase
  become: yes
  yum:
    name: keybase
    state: present
  when: is_rhel
