---

- name: Install Lollypop
  become: yes
  package:
    name: lollypop
    state: present
  when: ansible_facts["distribution"] == "Fedora" or ansible_facts["distribution"] == "Ubuntu"

- name: Install Lollypop
  become: yes
  flatpak:
    name: org.gnome.Lollypop
    state: present
  when: ansible_facts["distribution"] == "RedHat"
