---

- name: Install libva for hardware video offload
  become: yes
  dnf:
    name:
      - libva-intel-driver
      - libva-intel-hybrid-driver
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install dbus-tools for setting GNOME config programmatically
  become: yes
  dnf:
    name: dbus-tools
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install workstation apps and tools
  package:
    name:
      - gnome-tweaks
      - gimp
      - virt-viewer
      - virt-manager
      - mpv
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Install RedHat-specific workstation apps and tools
  dnf:
    name:
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - fuse-exfat
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Ubuntu-specific workstation apps and tools
  become: yes
  apt:
    name:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - exfat-fuse
      - ubuntu-restricted-extras
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- import_tasks: source_code_pro.yml
- import_tasks: lollypop.yml
- import_tasks: sublime.yml
- import_tasks: keybase.yml
- import_tasks: gnome.yml
