---

- name: Install flathub Flatpak remote
  become: yes
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: ansible_facts["os_family"] == "RedHat"

- name: Install dbus-tools for setting GNOME config programmatically
  become: yes
  dnf:
    name: dbus-tools
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install workstation apps and tools
  package:
    name:
      - gnome-tweaks
      - gimp
      - virt-viewer
      - virt-manager
      - mpv
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Install RedHat-specific workstation apps and tools
  dnf:
    name:
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - fuse-exfat
      - mozilla-fira-mono-fonts
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Ubuntu-specific workstation apps and tools
  become: yes
  apt:
    name:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - exfat-fuse
      - ubuntu-restricted-extras
      - fonts-firacode
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name: Homebrew/homebrew-cask-fonts
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      # For some reason, ansible can't find this but I can install manually...
      #- font-source-code-pro
      #- font-fira-mono
      #- font-iosevka
      - viscosity
      - imageoptim
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation CLI tools
  homebrew:
    name:
      - youtube-dl
      - ffmpeg
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- import_tasks: lollypop.yml
- import_tasks: signal.yml
- import_tasks: sublime.yml
- import_tasks: keybase.yml
- import_tasks: nextcloud.yml
- import_tasks: gnome.yml
- import_tasks: macos.yml
