---

- name: Install workstation GUI apps and related dependencies
  dnf:
    name:
      - adobe-source-code-pro-fonts
      - gnome-tweak-tool
      - gimp
      - firefox
      - virt-viewer
      - virt-manager
      - fuse-exfat
      - mpv
    state: present
  become: yes
  when: is_fedora

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name:
      - Homebrew/homebrew-cask-fonts
  when: is_macos

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      - whatsapp
      - homebrew/cask-versions/iterm2-beta
      - font-source-code-pro
      - 1password
      - viscosity
      - imageoptim
    state: present
  when: is_macos

- name: Download Source Code Pro manually
  become: yes
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: /usr/src/ascp.tar.gz
    remote_src: yes
  notify:
    - extract source code pro
    - install source code pro
    - update font cache
  when: is_ubuntu

- name: Install workstation GUI apps and related dependencies
  become: yes
  apt:
    name:
      - network-manager-openvpn
      - gnome-tweaks
      - gimp
      - firefox
      - virt-viewer
      - virt-manager
      - exfat-fuse
      - mpv
      - ubuntu-restricted-extras
    state: present
  when: is_ubuntu

- name: Install workstation CLI tools
  become: yes
  dnf:
    name:
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  when: is_fedora

- name: Install workstation CLI tools
  become: yes
  apt:
    name:
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  when: is_ubuntu

- name: Install workstation CLI tools
  homebrew:
    name:
      - youtube-dl
      - ffmpeg
    state: present
  when: is_macos

- import_tasks: lollypop.yml
- import_tasks: sublime.yml
- import_tasks: chrome.yml
- import_tasks: keybase.yml
- import_tasks: slack.yml
