---

- name: Install workstation GUI apps and related dependencies
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - gnome-tweak-tool
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - fuse-exfat
    - mpv
  when: is_fedora

- name: Install workstation GUI apps and related dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - gnome-tweak-tool
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - fuse-exfat
    - mpv
  when: is_rhel

- name: Install workstation CLI tools
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_fedora

- name: Install workstation CLI tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_rhel

- name: Install workstation CLI tools
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_ubuntu

- import_tasks: lollypop.yml
- import_tasks: sublime.yml
- import_tasks: chrome.yml
- import_tasks: keybase.yml
