---

- name: Install libva for hardware video offload
  become: yes
  dnf:
    name:
      - libva-intel-driver
      - libva-intel-hybrid-driver
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install dbus-tools for setting GNOME config programmatically
  become: yes
  dnf:
    name: dbus-tools
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install workstation GUI apps and related dependencies
  dnf:
    name:
      - adobe-source-code-pro-fonts
      - gnome-tweak-tool
      - gimp
      - firefox
      - virt-viewer
      - virt-manager
      - fuse-exfat
      - mpv
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Fedora"

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name:
      - Homebrew/homebrew-cask-fonts
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      - whatsapp
      - homebrew/cask-versions/iterm2-beta
      - font-source-code-pro
      - 1password
      - viscosity
      - imageoptim
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Download Source Code Pro manually
  become: yes
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: /usr/src/ascp.tar.gz
    remote_src: yes
  notify:
    - extract source code pro
    - install source code pro
    - update font cache
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install workstation GUI apps and related dependencies
  become: yes
  apt:
    name:
      - network-manager-openvpn
      - gnome-tweaks
      - gimp
      - firefox
      - virt-viewer
      - virt-manager
      - exfat-fuse
      - mpv
      - ubuntu-restricted-extras
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install workstation CLI tools
  become: yes
  dnf:
    name:
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install workstation CLI tools
  become: yes
  apt:
    name:
      - youtube-dl
      - powertop
      - ffmpeg
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install workstation CLI tools
  homebrew:
    name:
      - youtube-dl
      - ffmpeg
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- import_tasks: lollypop.yml
- import_tasks: sublime.yml
- import_tasks: chrome.yml
- import_tasks: keybase.yml

- import_tasks: gnome.yml
- import_tasks: macos.yml
