---

- name: Install workstation GUI apps and related dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - arc-theme
    - adobe-source-code-pro-fonts
    - gnome-tweak-tool
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - fuse-exfat

- name: Install workstation CLI tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - nmap
    - pass
    - powertop
    - ffmpeg
    - mpv

- include_tasks: lollypop.yml
- include_tasks: sublime.yml


# ------------------------------------------------------------------------------
# Direct RPM installations
#
# These all have manual checks for the executable because `yum` will download
# the RPM every time, since it can't know if the version we have install is the
# same as the remote resource).
# ------------------------------------------------------------------------------

- name: Check for Keybase
  command: stat /usr/bin/keybase
  register: has_keybase
  changed_when: no
  failed_when: has_keybase.rc > 1
- name: Install keybase
  yum:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
  become: yes
  when: has_keybase == 1

- name: Check for Google Chrome
  command: stat /usr/bin/google-chrome
  register: has_chrome
  changed_when: no
  failed_when: has_chrome.rc > 1
- name: Install Google Chrome
  yum:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
  become: yes
  when: has_chrome == 1

- name: Check for zoom
  command: stat /usr/bin/zoom
  register: has_zoom
  changed_when: no
  failed_when: has_zoom.rc > 1
- name: Install Zoom Meetings Client
  yum:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
    state: present
  become: yes
  when: has_zoom.rc == 1
