---

- name: Install workstation GUI apps and related dependencies
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - gnome-tweak-tool
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - fuse-exfat
    - mpv
  when: is_fedora

- name: Install workstation GUI apps and related dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - gnome-tweak-tool
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - fuse-exfat
    - mpv
  when: is_rhel

- name: Download Source Code Pro manually
  become: yes
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: /usr/src/ascp.tar.gz
    remote_src: yes
  notify:
    - extract source code pro
    - install source code pro
    - update font cache
  when: is_ubuntu

- name: Download Fira Sans manually
  become: yes
  get_url:
    url: https://github.com/mozilla/Fira/archive/master.zip
    dest: /usr/src/fira.tar.gz
    remote_src: yes
  notify:
    - extract fira
    - install fira
    - update font cache
  when: is_ubuntu

- name: Install workstation GUI apps and related dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-tweaks
    - gimp
    - firefox
    - virt-viewer
    - virt-manager
    - exfat-fuse
    - mpv
  when: is_ubuntu

- name: Install workstation CLI tools
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_fedora

- name: Install workstation CLI tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_rhel

- name: Install workstation CLI tools
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - youtube-dl
    - pass
    - powertop
    - ffmpeg
  when: is_ubuntu

- import_tasks: lollypop.yml
- import_tasks: sublime.yml
- import_tasks: chrome.yml
- import_tasks: keybase.yml
