---

- name: Download Source Code Pro manually
  become: yes
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: /usr/src/ascp.tar.gz
    remote_src: yes
  notify:
    - extract source code pro
    - install source code pro
    - update font cache
  when: ansible_facts["distribution"] == "Ubuntu" or ansible_facts["distribution"] == "RedHat"

- name: Install Source Code Pro
  dnf:
    name: adobe-source-code-pro-fonts
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Fedora"
