---

- name: Install Spotify
  become: yes
  snap:
    name: spotify
    state: present
  when: ansible_facts["os_family"] != "Darwin"

- name: Install Spotify
  homebrew_cask:
    name: spotify
    state: present
  when: ansible_facts["os_family"] == "Darwin"
