---

# -------------------------------------------------------------------------
# General config
# -------------------------------------------------------------------------

- name: "disable gross vim defaults"
  copy:
    dest: /etc/vimrc
    content: ""
  become: yes

- name: "disable stupid ls colors"
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: yes

# For some reason, dnf doesn't like installing groups here, so we've
# included "C development tools and libraries" manually...
- name: "Install some development tools and libraries"
  dnf:
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - git
    - tmux
    - vim
    - the_silver_searcher
    - pass
    - pwgen
    - optipng
    - htop
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - nmap
    - ImageMagick
    - perf
    - dstat
    - redhat-rpm-config
    - rpm-build
    - python-devel
    - autoconf
    - automake
    - binutils
    - bison
    - flex
    - gcc
    - gcc-c++
    - gdb
    - glibc-devel
    - libtool
    - make
    - maven
    - pkgconfig
    - strace
    - ruby-devel
    - nodejs
    - sqlite-devel
    - rust
    - cargo

- import_tasks: ../shared/development.yml


# -------------------------------------------------------------------------
# Erlang
# -------------------------------------------------------------------------

- name: "Install Erlang"
  dnf:
    name: erlang
    state: latest
  become: yes


# -------------------------------------------------------------------------
# PostgreSQL
# -------------------------------------------------------------------------

- name: "Install postgresql server and client libs"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-devel
    - postgresql-server
    - postgresql-contrib
  become: yes

- name: "Initialize PostgreSQL data directory"
  command: "postgresql-setup --initdb --unit postgresql"
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: yes

- name: "Add custom pg_hba.conf to allow password auth"
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
  become: yes
  notify:
    - restart postgresql

- name: "Enable and start postresql"
  service:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: "Add superuser role for default user"
  postgresql_user:
    name: "{{ user }}"
    role_attr_flags: SUPERUSER,LOGIN
    state: present
  become: yes
  become_user: postgres


# -------------------------------------------------------------------------
# Redis
# -------------------------------------------------------------------------
- name: "Install redis"
  dnf:
    name: redis
    state: present
  become: yes

- name: "Enable and start redis"
  service:
    name: redis
    state: started
    enabled: yes
  become: yes


# -------------------------------------------------------------------------
# Ruby
# -------------------------------------------------------------------------

- import_tasks: ../shared/rubbies.yml


# -------------------------------------------------------------------------
# Python
# -------------------------------------------------------------------------

- name: "Install python and some libs"
  dnf:
    name: "{{ item }}"
  with_items:
    - python3-devel
    - python2-virtualenv
    - python-pygments
  become: yes
