---

- name: "disable gross vim defaults"
  copy:
    dest: /etc/vimrc
    content: ""
  become: true

- name: "disable stupid ls colors"
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: true
