---

- name: "Install postgresql server and client libs"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-devel
    - postgresql-server
    - postgresql-contrib
  become: true

- name: "Initialize PostgreSQL data directory"
  command: "postgresql-setup --initdb --unit postgresql"
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf
  become: true

- name: "Enable and start postresql"
  service:
    name: postgresql
    enabled: yes
    state: started
  become: true

- name: "Add superuser role for default user"
  postgresql_user:
    name: "{{ user }}"
    role_attr_flags: SUPERUSER,LOGIN
    state: present
  become: true
  become_user: postgres
