---

- name: Always expand save dialogues' file browser
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

- name: Disable autocorrect
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Show all file extensions in Finder
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Show status bar in Finder.app
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Don't warn when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Enable text selection in QuickLook
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

- name: Enable devtools in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true

- name: Enable devtools in all webkits
  osx_defaults:
    key: WebKitDeveloperExtras
    type: bool
    value: true

- name: Make time machine shut up
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true

- name: Make key repeat real fast
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 0

- name: Enable tab to all controls
  osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 3

- name: Don't spew .DS_Store files into my network mounts
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Open mission control when slamming into the top-left screen corner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 2

- name: Don't require a modifier for the aforementioned top-left hotcorner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0

- name: Disable Siri status bar icon
  osx_defaults:
    domain: com.apple.Siri
    key: StatusMenuVisible
    type: bool
    value: false

- name: Tell Siri we don't want it
  osx_defaults:
    domain: com.apple.Siri
    key: UserHasDeclinedEnable
    type: bool
    value: true

- name: Disable Siri Assistant
  osx_defaults:
    domain: com.apple.assistant.support
    key: 'Assistant Enabled'
    type: int
    value: 0

###############################################################################
# Things I used to set, but am not sure if I want.
###############################################################################

- name: Disable window opening animations
  osx_defaults:
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: false
  when: False

- name: Show hidden files in Finder
  osx_defaults:
    domain: com.apple.Finder
    key: AppleShowAllFiles
    type: bool
    value: true
  when: False

- name: Don't save windows when quitting apps
  osx_defaults:
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false
  when: False

- name: Allow restarting/quitting Finder.app
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
  when: False

- name: Enable browsing the network across all network connections
  osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true
  when: False

- name: Don't relaunch apps on login
  osx_defaults:
    domain: com.apple.loginwindow
    key: LoginwindowLaunchesRelaunchApps
    type: bool
    value: false
  when: False

- name: Don't save state of apps on logout
  osx_defaults:
    domain: com.apple.loginwindow
    key: TALLogoutSavesState
    type: bool
    value: false
  when: False
