---

- name: Install the heroku-cli
  become: yes
  unarchive:
    src: https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/heroku/bin/heroku
  when: is_fedora or is_ubuntu

- name: Install Terraform
  homebrew:
    name: terraform
    state: present
  when: is_macos

- name: Install Heroku CLI
  homebrew:
    name: heroku/brew/heroku
    state: present
  when: is_macos

- name: Install Terraform
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/terraform
  when: is_fedora or is_ubuntu

- name: Add Heroku CLI to PATH
  become: yes
  copy:
    content: export PATH=/usr/local/heroku/bin:$PATH
    dest: /etc/profile.d/heroku.sh
    mode: 0755
  when: is_fedora or is_ubuntu
