---

- name: Install the heroku-cli
  become: yes
  shell: curl -Ls https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz | tar xzC /usr/local
  args:
    creates: /usr/local/heroku/bin/heroku

- name: Install Terraform
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/terraform

- name: Add Heroku CLI to PATH
  become: yes
  copy:
    content: export PATH=/usr/local/heroku/bin:$PATH
    dest: /etc/profile.d/heroku.sh
    mode: 0755
