---

- name: Install the heroku-cli
  become: yes
  unarchive:
    src: https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/heroku/bin/heroku
  when: ansible_facts["distribution"] == "Fedora" or ansible_facts["distribution"] == "Ubuntu"
  tags:
  - cloud

- name: Add Heroku CLI to PATH
  become: yes
  copy:
    content: export PATH=/usr/local/heroku/bin:$PATH
    dest: /etc/profile.d/heroku.sh
    mode: 0755
  when: ansible_facts["distribution"] == "Fedora" or ansible_facts["distribution"] == "Ubuntu"
  tags:
  - cloud

- name: Install Heroku CLI
  homebrew:
    name: heroku/brew/heroku
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
  - cloud
  - package
