---

- name: Clone dotfiles
  git:
    repo: https://github.com/alexblackie/dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: yes
    update: no
  tags:
  - dotfiles

- name: Install dotfiles
  shell: FORCE=1 ./install
  args:
    chdir: "{{ home }}/.dotfiles"
    creates: "{{ home }}/.commonrc"
  tags:
  - dotfiles

- name: Restore dconf configuration
  shell: ./dconf && touch ~/.completed_initial_dconf_restore
  args:
    chdir: "{{ home }}/.dotfiles"
    creates: "{{ home }}/.completed_initial_dconf_restore"
  tags:
  - dotfiles
  when: should_dconf and (ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu")
