---

- name: Clone dotfiles
  git:
    repo: https://projects.blackieops.com/alexblackie/dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: yes
    update: no

- name: Install dotfiles
  shell: make && make install && make dconf
  args:
    chdir: "{{ home }}/.dotfiles"
    creates: "{{ home }}/.commonrc"
