---

# TODO: ubuntu

- name: Add Microsoft repo
  become: true
  yum_repository:
    name: packages-microsoft-com-prod
    description: packages.microsoft.com
    #baseurl: "https://packages.microsoft.com/fedora/{{ ansible_facts['distribution_major_version'] }}/prod/"
    # No 31 repo available at time of writing
    baseurl: "https://packages.microsoft.com/fedora/30/prod/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
  when: ansible_facts["distribution"] == "Fedora"
  tags:
  - packages
  - dotnet
  - dev

- name: Install .NET Core SDK
  become: true
  package:
    name:
    - dotnet-sdk-2.2
    - dotnet-sdk-3.0
    state: present
  when: ansible_facts["distribution"] == "Fedora"
  tags:
  - packages
  - dotnet
  - dev
