---

- name: Clone fzy
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: "{{ home }}/src/fzy"
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Compile and install fzy
  shell: make && make install
  become: yes
  args:
    chdir: "{{ home }}/src/fzy"
    creates: /usr/local/bin/fzy
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"
