---

- name: Install JDK and tools
  dnf:
    name:
      - java-latest-openjdk
      - java-latest-openjdk-devel
      - maven
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install JDK and tools
  apt:
    name:
      - default-jdk
      - maven
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"
