---

- name: disable gross vim defaults
  copy:
    dest: /etc/vimrc
    content: ""
  become: yes
  when: is_fedora or is_rhel

- name: disable stupid ls colors
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: yes
  when: is_fedora or is_rhel

- name: Create directory for third-party software sources
  file:
    path: "{{ home }}/src"
    state: directory

- name: Create local bin directory
  file:
    path: "{{ home }}/bin"
    state: directory

- name: Install C toolchain
  become: yes
  dnf:
    name: "@C Development Tools and Libraries"
    state: present
  when: is_fedora

- name: Install C toolchain
  become: yes
  yum:
    name: "@Development Tools"
    state: present
  when: is_rhel

- name: Install C toolchain
  become: yes
  apt:
    name: build-essential
    state: present
  when: is_ubuntu

- name: Install some development tools and libraries
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - git
    - tmux
    - vim
    - the_silver_searcher
    - pwgen
    - optipng
    - nmap
    - ImageMagick
    - ImageMagick-devel
    - sqlite-devel
  when: is_rhel

- name: Install some development tools and libraries
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - git
    - tmux
    - vim
    - the_silver_searcher
    - pwgen
    - optipng
    - nmap
    - ImageMagick
    - ImageMagick-devel
    - sqlite-devel
  when: is_fedora

- name: Install some development tools and libraries
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - git
    - git-doc
    - tmux
    - vim
    - curl # lmao ubuntu doesn't come with curl by default??
    - silversearcher-ag
    - pwgen
    - optipng
    - nmap
    - imagemagick
    - libmagickwand-dev
    - libsqlite3-dev
  when: is_ubuntu

- name: Install system visibility tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - perf
    - dstat
    - strace
  when: is_rhel

- name: Install system visibility tools
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - perf
    - dstat
    - strace
  when: is_fedora

- name: Install system visibility tools
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - linux-tools-generic
    - dstat
    - strace
  when: is_ubuntu

- name: Install snapd
  become: yes
  dnf:
    name: snapd
    state: present
  when: is_fedora

- import_tasks: postgresql_rhel.yml
  when: is_rhel
- import_tasks: postgresql_fedora.yml
  when: is_fedora
- import_tasks: postgresql_ubuntu.yml
  when: is_ubuntu

- import_tasks: redis.yml

- import_tasks: ruby.yml
- import_tasks: erlang.yml
- import_tasks: python.yml
- import_tasks: java.yml
- import_tasks: redhat.yml
- import_tasks: nodejs.yml
- import_tasks: rust.yml
- import_tasks: latex.yml

- import_tasks: cloud_trash.yml
- import_tasks: fzy.yml

- import_tasks: dotfiles.yml
