---

- name: disable gross vim defaults
  copy:
    dest: /etc/vimrc
    content: ""
  become: yes

- name: disable stupid ls colors
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: yes

- name: Create directory for third-party software sources
  file:
    path: "{{ home }}/src"
    state: directory

- name: Create local bin directory
  file:
    path: "{{ home }}/bin"
    state: directory

- name: Install C toolchain
  become: yes
  dnf:
    name: "@C Development Tools and Libraries"
    state: present
  when: is_fedora is defined

- name: Install C toolchain
  become: yes
  yum:
    name: "@Development Tools"
    state: present
  when: is_rhel is defined

- name: "Install some development tools and libraries"
  yum:
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - git
    - tmux
    - vim
    - the_silver_searcher
    - pwgen
    - optipng
    - htop
    - ImageMagick
    - perf
    - dstat
    - redhat-rpm-config
    - rpm-build
    - pkgconfig
    - strace
    - ruby-devel
    - nodejs
    - sqlite-devel

- import_tasks: postgresql_rhel.yml
  when: is_rhel is defined
- import_tasks: postgresql_fedora.yml
  when: is_fedora is defined

- import_tasks: ruby.yml
- import_tasks: erlang.yml
- import_tasks: java.yml

- import_tasks: cloud_trash.yml
- import_tasks: fzy.yml
