---

- name: install zsh
  become: yes
  package:
    name: zsh
    state: present
  when: ansible_facts["distribution"] == "Ubuntu" or ansible_facts["os_family"] == "RedHat"

- name: set default shell to zsh
  become: yes
  user:
    name: "{{ local_user }}"
    shell: /usr/bin/zsh

- name: disable gross vim defaults
  copy:
    dest: /etc/vimrc
    content: ""
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: disable stupid ls colors
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Create directory for third-party software sources
  file:
    path: "{{ third_party_src }}"
    state: directory

- name: Create local bin directory
  file:
    path: "{{ home }}/bin"
    state: directory

- name: Install C toolchain
  become: yes
  dnf:
    name: "@C Development Tools and Libraries"
    state: present
  when: ansible_facts["distribution"] == "Fedora"

# The "development tools" group in RHEL is enormous and I don't want most of it.
- name: Install C toolchain
  become: yes
  dnf:
    name:
      - binutils
      - bison
      - flex
      - gcc
      - gcc-c++
      - make
      - pkgconfig
    state: present
  when: ansible_facts["distribution"] == "RedHat"

- name: Install C toolchain
  become: yes
  apt:
    name: build-essential
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"


- name: Install some development tools and libraries
  become: yes
  dnf:
    name:
      - ruby-devel
      - automake
      - autoconf
      - wxGTK3-devel
      - wxBase3
      - readline-devel
      - ncurses-devel
      - openssl-devel
      - libyaml-devel
      - libxslt-devel
      - libffi-devel
      - libtool
      - unixODBC-devel
      - git
      - tmux
      - vim
      - pwgen
      - optipng
      - nmap
      - ImageMagick
      - ImageMagick-devel
      - sqlite-devel
      - inotify-tools
      - jq
      - whois
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install some development tools and libraries
  become: yes
  dnf:
    name:
      - the_silver_searcher
      - entr
      - ShellCheck
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install some development tools and libraries
  become: yes
  apt:
    name:
      - ruby-dev
      - automake
      - autoconf
      - libwxgtk3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libreadline-dev
      - libncurses5-dev
      - libssl-dev
      - libyaml-dev
      - libxslt-dev
      - libffi-dev
      - libtool
      - unixodbc-dev
      - git
      - git-doc
      - tmux
      - vim
      - curl
      - silversearcher-ag
      - pwgen
      - optipng
      - nmap
      - imagemagick
      - libmagickwand-dev
      - sqlite3
      - libsqlite3-dev
      - inotify-tools
      - entr
      - whois
      - ethtool
      - jq
      - shellcheck
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install system visibility tools
  become: yes
  dnf:
    name:
      - htop
      - perf
      - strace
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install system visibility tools
  become: yes
  apt:
    name:
      - htop
      - linux-tools-generic
      - dstat
      - strace
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install gawk
  become: yes
  apt:
    name: gawk
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Ensure we're using gawk
  become: yes
  alternatives:
    name: awk
    path: /usr/bin/gawk
  when: ansible_facts["distribution"] == "Ubuntu"

- import_tasks: postgresql_redhat.yml
  when: ansible_facts["os_family"] == "RedHat"
- import_tasks: postgresql_ubuntu.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- import_tasks: redis.yml
- import_tasks: drone.yml
- import_tasks: fzy.yml
- import_tasks: ag.yml

- import_tasks: asdf.yml

- import_tasks: python.yml
- import_tasks: java.yml
- import_tasks: redhat.yml

- import_tasks: dotfiles.yml
