---

- name: disable gross vim defaults
  copy:
    dest: /etc/vimrc
    content: ""
  become: yes
  when: is_fedora

- name: disable stupid ls colors
  copy:
    dest: /etc/profile.d/colorls.sh
    content: ""
  become: yes
  when: is_fedora

- name: Create directory for third-party software sources
  file:
    path: "{{ home }}/src"
    state: directory

- name: Create local bin directory
  file:
    path: "{{ home }}/bin"
    state: directory

- name: Install C toolchain
  become: yes
  dnf:
    name: "@C Development Tools and Libraries"
    state: present
  when: is_fedora

- name: Install C toolchain
  become: yes
  apt:
    name: build-essential
    state: present
  when: is_ubuntu

- name: Install asdf version manager
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.6.0
    dest: "{{ home }}/.asdf"
    update: yes

- name: Install some development tools and libraries
  become: yes
  dnf:
    name:
      - ruby-devel
      - automake
      - autoconf
      - wxGTK3-devel
      - wxBase3
      - readline-devel
      - ncurses-devel
      - openssl-devel
      - libyaml-devel
      - libxslt-devel
      - libffi-devel
      - libtool
      - unixODBC-devel
      - git
      - tmux
      - vim
      - the_silver_searcher
      - pwgen
      - optipng
      - nmap
      - ImageMagick
      - ImageMagick-devel
      - sqlite-devel
      - inotify-tools
      - entr
      - jq
      - ShellCheck
    state: present
  when: is_fedora

- name: Install some development tools and libraries
  become: yes
  apt:
    name:
      - ruby-dev
      - automake
      - autoconf
      - libwxgtk3.0-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libreadline-dev
      - libncurses-dev
      - libssl-dev
      - libyaml-dev
      - libxslt-dev
      - libffi-dev
      - libtool
      - unixodbc-dev
      - git
      - git-doc
      - tmux
      - vim
      - curl
      - silversearcher-ag
      - pwgen
      - optipng
      - nmap
      - imagemagick
      - libmagickwand-dev
      - sqlite3
      - libsqlite3-dev
      - inotify-tools
      - entr
      - whois
      - ethtool
      - jq
      - shellcheck
    state: present
  when: is_ubuntu

- name: Install some development tools and libraries
  homebrew:
    name:
      - findutils
      - autoconf
      - wxmac
      - git
      - tmux
      - reattach-to-user-namespace
      - vim
      - curl
      - wget
      - the_silver_searcher
      - pwgen
      - optipng
      - nmap
      - imagemagick
      - sqlite
      - htop
      - jq
      - shellcheck
    state: present
  when: is_macos

- name: Install system visibility tools
  become: yes
  dnf:
    name:
      - htop
      - perf
      - strace
    state: present
  when: is_fedora

- name: Install system visibility tools
  become: yes
  apt:
    name:
      - htop
      - linux-tools-generic
      - dstat
      - strace
    state: present
  when: is_ubuntu

- name: Install snapd
  become: yes
  dnf:
    name: snapd
    state: present
  when: is_fedora

- name: Install gawk
  become: yes
  apt:
    name: gawk
    state: present
  when: is_ubuntu

- name: Ensure we're using gawk
  become: yes
  alternatives:
    name: awk
    path: /usr/bin/gawk
  when: is_ubuntu

- import_tasks: postgresql_fedora.yml
  when: is_fedora
- import_tasks: postgresql_ubuntu.yml
  when: is_ubuntu
- import_tasks: postgresql_macos.yml
  when: is_macos

- import_tasks: redis.yml

- import_tasks: python.yml
- import_tasks: java.yml
- import_tasks: redhat.yml
- import_tasks: latex.yml

- import_tasks: cloud_trash.yml
- import_tasks: fzy.yml
- import_tasks: zod.yml

- import_tasks: dotfiles.yml
