---

- name: Install nodejs and tools
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm
  when: is_rhel

- name: Install nodejs and tools
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm
  when: is_fedora
