---

- name: Add PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
    state: present
  become: yes

- name: Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-contrib
    - postgresql96-devel
    - python-psycopg2

- name: Initialize PostgreSQL data directory
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  args:
    creates: /var/lib/pgsql/9.6/data/postgresql.conf
  become: yes

- name: Add custom pg_hba.conf to allow password auth
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
  become: yes
  notify:
    - restart postgresql-9.6

- name: Enable and start postresql
  service:
    name: postgresql-9.6
    enabled: yes
    state: started
  become: yes

- name: Add superuser role for default user
  postgresql_user:
    name: "{{ user }}"
    role_attr_flags: SUPERUSER,LOGIN
    state: present
  become: yes
  become_user: postgres
