---

- name: Install PostgreSQL server and client
  homebrew:
    name:
      - postgresql
      - libpq
    state: present

# TODO this path can't be right...
- name: Add custom pg_hba.conf to allow password auth
  template:
    src: pg_hba.conf.j2
    dest: /usr/local/etc/postgresql/pg_hba.conf
  become: yes
  notify:
    - brew restart postgresql
