---

- name: Install postgresql server and client libs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-psycopg2
    - postgresql
    - libpq-dev
    - postgresql-client
    - postgresql-contrib
  become: yes

- name: Add custom pg_hba.conf to allow password auth
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/10/main/pg_hba.conf
  become: yes
  notify:
    - restart postgresql

- name: Enable and start postresql
  service:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: Add superuser role for default user
  postgresql_user:
    name: "{{ user }}"
    role_attr_flags: SUPERUSER,LOGIN
    state: present
  become: yes
  become_user: postgres
