---

- name: Install Python and some libs
  dnf:
    name:
      - python
      - python-devel
      - python-virtualenv
      - python-pip
      - python-pygments
      - python3
      - python3-devel
  become: yes
  when: ansible_facts["distribution"] == "Fedora"

- name: Install Python and some libs
  apt:
    name:
      - python
      - python-dev
      - python-virtualenv
      - python-pip
      - python-pygments
      - python3
      - python3-dev
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install some Python CLI tools
  pip:
    name:
      - awscli
      - httpstat
    state: present
  become: yes
