---

- name: Install tools for RPM development
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - redhat-rpm-config
    - rpm-build
    - pkgconfig
  when: is_rhel

- name: Install tools for RPM development
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - redhat-rpm-config
    - rpm-build
    - pkgconfig
  when: is_fedora
