---

- name: Install redis
  dnf:
    name: redis
    state: present
  become: yes
  when: is_fedora

- name: Install redis
  apt:
    name: redis-server
    state: present
  become: yes
  when: is_ubuntu

- name: Install redis
  become: yes
  homebrew:
    name: redis
    state: present
  when: is_macos

- name: Enable and start redis
  service:
    name: redis
    state: started
    enabled: yes
  become: yes
  when: is_fedora

- name: Enable and start redis
  service:
    name: redis-server
    state: started
    enabled: yes
  become: yes
  when: is_ubuntu

- name: Enable and start redis
  homebrew_service:
    name: redis
    state: started
    enabled: yes
  when: is_macos
