---

- name: Install redis
  dnf:
    name: redis
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install redis
  apt:
    name: redis-server
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Enable and start redis
  service:
    name: redis
    state: started
    enabled: yes
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Enable and start redis
  service:
    name: redis-server
    state: started
    enabled: yes
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"
