---

- name: Install BlackieOps Trust Root
  become: yes
  get_url:
    url: https://trust.blackieops.com/blackieops_trust_chain_2017.pem
    dest: /etc/pki/ca-trust/source/anchors/blackieops_trust_chain_2017.pem
  notify:
    - update ca-trust
  when: is_fedora

- name: Install BlackieOps Trust Root
  become: yes
  get_url:
    url: https://trust.blackieops.com/blackieops_trust_chain_2017.pem
    dest: /usr/local/share/ca-certificates/blackieops_trust_chain_2017.pem
  notify:
    - update-ca-certificates
  when: is_ubuntu

- name: Install BlackieOps Trust Root
  become: yes
  get_url:
    url: https://trust.blackieops.com/blackieops_trust_chain_2017.pem
    dest: /tmp/blackieops.pem
  notify:
    - update keychain
  when: is_macos
