---

- name: Install securedata script for mounting SD card
  become: true
  template:
    src: securedata
    dest: /usr/local/bin/securedata
    mode: 0755

- name: Clone Vimix theme
  git:
    repo: https://github.com/vinceliuice/vimix-gtk-themes.git
    dest: "{{ home }}/src/vimix"
    update: no
    accept_hostkey: yes
- name: Clone Vimix icons
  git:
    repo: https://github.com/vinceliuice/vimix-icon-theme.git
    dest: "{{ home }}/src/vimix-icons"
    update: no
    accept_hostkey: yes
- name: Install vimix theme
  command: ./Install
  become: yes
  args:
    creates: /usr/share/themes/Vimix-Dark
    chdir: "{{ home }}/src/vimix"
- name: Install vimix icon theme
  command: cp -a Vimix Paper-Vimix /usr/share/icons/
  become: yes
  args:
    creates: /usr/share/icons/Vimix
    chdir: "{{ home }}/src/vimix-icons"
- name: Enable vimix gtk theme
  command: gsettings set org.gnome.desktop.interface gtk-theme VimixDark-Doder
- name: Enable vimix window theme
  command: gsettings set org.gnome.desktop.wm.preferences theme VimixDark-Doder
- name: Enable vimix icon theme
  command: gsettings set org.gnome.desktop.interface icon-theme Vimix

- command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
- command: gsettings set org.gnome.desktop.interface clock-show-date true
- command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
- command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

- git:
    repo: https://github.com/alexblackie/gextension.git
    dest: "{{home}}/.gextension"
    accept_hostkey: yes
    update: no
- name: "install GNOME extensions"
  shell: "./gextension install {{item}}"
  args:
    chdir: "{{home}}/.gextension"
  with_items:
    - sound-output-device-chooser@kgshank.net
    - dash-to-dock@micxgx.gmail.com
    - caffeine@patapon.info
    - impatience@gfxmonk.net
