---
- name: "temp directory for storing source code archives of compiled warez"
  file:
    path: "{{ home }}/src"
    state: directory

- name: "local bin directory"
  file:
    path: "{{ home }}/bin"
    state: directory

- name: "Install some python tools"
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - awscli
    - httpstat

- name: "Install the heroku-cli"
  shell: curl -Ls https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz | tar xzC {{home}}/bin
  args:
    creates: "{{ home }}/bin/heroku"


- name: "Install Terraform"
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
    dest: "{{ home }}/bin/"
    remote_src: yes
  creates: "{{ home }}/bin/terraform"

- name: "Create user env file"
  file:
    path: "{{ home }}/.env"
    state: touch
- name: "Add Heroku CLI to PATH"
  lineinfile:
    line: export PATH=$HOME/bin/heroku/bin:$PATH
    dest: "{{ home }}/.env"

- name: "Clone fzy"
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: "{{ home }}/src/fzy"
- name: "Compile and install fzy"
  shell: "make && make install"
  become: true
  args:
    chdir: "{{ home }}/src/fzy"
