---
- group: name="docker"
  become: true

- user:
    name: "{{user}}"
    groups: docker
    append: yes
  become: true

- service:
    name: docker
    enabled: yes
    state: started
  become: true
