---

- name: Install Ruby for gextension
  become: yes
  yum:
    name: ruby
    state: present
  when: is_rhel

- name: Install Ruby for gextension
  become: yes
  dnf:
    name: ruby
    state: present
  when: is_fedora

- name: Install Ruby for gextension
  become: yes
  apt:
    name: ruby
    state: present
  when: is_ubuntu

- name: Install psutil for dconf integration
  become: yes
  dnf:
    name: python-psutil
    state: present
  when: is_fedora

- name: Install psutil for dconf integration
  become: yes
  apt:
    name: python-psutil
    state: present
  when: is_ubuntu

- name: Set various GNOME dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:escape', 'compose:rctrl']"
    - key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
    - key: "/org/gnome/software/allow-updates"
      value: "false"
    - key: "/org/gnome/software/download-updates"
      value: "false"
    - key: "/org/gnome/terminal/legacy/default-show-menubar"
      value: "false"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/desktop/search-providers/disable-external"
      value: "true"
    - key: "/org/gnome/shell/favorite-apps"
      value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'sublime_text.desktop', 'firefox.desktop', 'org.gnome.Lollypop.desktop']"

- name: Clean out a bunch of GNOME junk
  become: yes
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - evolution
    - evolution-ews
    - evolution-help
    - gfbgraph
    - gnome-boxes
    - gnome-calendar
    - gnome-contacts
    - gnome-dictionary
    - gnome-documents
    - gnome-getting-started-docs
    - gnome-initial-setup
    - gnome-online-miners
    - gnome-photos
    - gnome-software
    - gnome-user-docs
    - gnome-weather
    - simple-scan
    - totem
    - tracker-miners
    - yelp
  when: is_fedora

- name: Ensure we didn't accidentally remove Gnome itself
  become: yes
  dnf:
    name:
      - eog
      - evince
      - flatpak
      - gdm
      - gnome-keyring
      - gnome-menus
      - gnome-screenshot
      - gnome-shell
      - gnome-terminal
      - gnome-tweaks
      - nautilus
      - redhat-menus
    state: present
  when: is_fedora

- name: Mask a bunch of GNOME junk
  systemd:
    name: "{{ item }}"
    user: yes
    masked: yes
    state: stopped
  with_items:
    - evolution-addressbook-factory.service
    - evolution-calendar-factory.service
    - evolution-source-registry.service

# tracker is only used on Fedora/RHEL
- name: Mask tracker indexer
  systemd:
    name: tracker-store.service
    user: yes
    masked: yes
    state: stopped
  when: is_fedora or is_rhel

- name: Install gextension
  git:
    repo: https://projects.blackieops.com/alexblackie/gextension.git
    dest: "{{ home }}/.gextension"
    accept_hostkey: yes
    update: yes

- name: Install GNOME extensions
  shell: ./gextension install {{ item }}
  args:
    chdir: "{{ home }}/.gextension"
  with_items:
    - sound-output-device-chooser@kgshank.net
    - caffeine@patapon.info
