---

- name: Install Ruby for gextension
  become: yes
  yum:
    name: ruby
    state: present
  when: is_rhel

- name: Install Ruby for gextension
  become: yes
  dnf:
    name: ruby
    state: present
  when: is_fedora

- name: Install Ruby for gextension
  become: yes
  apt:
    name: ruby
    state: present
  when: is_ubuntu

- name: Install psutil for dconf integration
  become: yes
  dnf:
    name: python-psutil
    state: present
  when: is_fedora

- name: Install psutil for dconf integration
  become: yes
  pip:
    name: psutil
    state: present
  when: is_rhel

- name: Install psutil for dconf integration
  become: yes
  apt:
    name: python-psutil
    state: present
  when: is_ubuntu

- name: Set various GNOME dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:escape', 'compose:rctrl']"
    - key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
    - key: "/org/gnome/software/allow-updates"
      value: "false"
    - key: "/org/gnome/software/download-updates"
      value: "false"
    - key: "/org/gnome/terminal/legacy/default-show-menubar"
      value: "false"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/shell/favorite-apps"
      value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'sublime_text.desktop', 'firefox.desktop', 'claws-mail.desktop', 'org.gnome.Lollypop.desktop', 'slack.desktop']"
    - key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
      value: "false"

- name: Install gextension
  git:
    repo: https://projects.blackieops.com/alexblackie/gextension.git
    dest: "{{ home }}/.gextension"
    accept_hostkey: yes
    update: yes

- name: Install GNOME extensions
  shell: ./gextension install {{ item }}
  args:
    chdir: "{{ home }}/.gextension"
  with_items:
    - sound-output-device-chooser@kgshank.net
    - caffeine@patapon.info
