---

- name: Install Ruby for gextension
  become: yes
  yum:
    name: ruby
    state: present
  when: is_rhel

- name: Install Ruby for gextension
  become: yes
  dnf:
    name: ruby
    state: present
  when: is_fedora

- name: Set various GNOME dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:escape', 'compose:rctrl']"
    - key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
    - key: "/org/gnome/software/allow-updates"
      value: "false"
    - key: "/org/gnome/software/download-updates"
      value: "false"
    - key: "/org/gnome/terminal/legacy/default-show-menubar"
      value: "false"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/desktop/search-providers/disable-external"
      value: "true"

- name: Install gextension
  git:
    repo: https://github.com/alexblackie/gextension.git
    dest: "{{ home }}/.gextension"
    accept_hostkey: yes
    update: no
- name: Install GNOME extensions
  shell: ./gextension install {{item}}
  args:
    chdir: "{{ home }}/.gextension"
  with_items:
    - sound-output-device-chooser@kgshank.net
    - dash-to-panel@jderose9.github.com
    - caffeine@patapon.info
