---

- name: Install psutil for dconf integration
  become: yes
  dnf:
    name:
      - python2-psutil
      - python3-psutil
    state: present
  when: is_fedora

- name: Install psutil for dconf integration
  become: yes
  apt:
    name: python-psutil
    state: present
  when: is_ubuntu

- name: Set various GNOME dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:escape', 'compose:rctrl']"
    - key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
    - key: "/org/gnome/software/allow-updates"
      value: "false"
    - key: "/org/gnome/software/download-updates"
      value: "false"
    - key: "/org/gnome/terminal/legacy/default-show-menubar"
      value: "false"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
      value: "false"
