---

- name: extract source code pro
  become: yes
  unarchive:
    src: /usr/src/ascp.tar.gz
    dest: /usr/src/

- name: install source code pro
  become: yes
  copy:
    src: /usr/src/source-code-pro-2.030R-ro-1.050R-it/OTF/
    dest: /usr/share/fonts/

- name: update font cache
  become: yes
  command: fc-cache -f
