---

- name: Install QEMU and Libvirt
  become: yes
  dnf:
    name:
      - qemu-kvm
      - libvirt
    state: present
  when: is_fedora

- name: Enable and start libvirtd
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes
  when: is_fedora
