---

- include_vars: "{{ ansible_facts['os_family'] }}.yml"
  tags:
  - virt

- name: Install QEMU and libvirt
  become: yes
  package:
    name:
    - qemu-kvm
    - "{{ libvirt_package_name }}"
    state: present
  tags:
  - virt
  - packages

- name: Enable and start libvirtd
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - virt
