---

- name: Install QEMU and Libvirt
  become: yes
  dnf:
    name:
      - qemu-kvm
      - libvirt
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Enable and start libvirtd
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes
  when: ansible_facts["distribution"] == "Fedora"
