---

- name: Install Docker
  yum:
    name: docker
    state: present
  become: yes
  when: is_rhel

- name: Install Docker
  dnf:
    name: docker
    state: present
  become: yes
  when: is_fedora

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes
  when: is_ubuntu

# RHEL doesn't package docker-compose and the official Docker repos don't
# package Docker CE for RHEL (thank's, greedy biz asshats)
- name: Install docker-compose
  become: yes
  pip:
    name: docker-compose
    state: present

- name: Ensure presence of docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add local user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes

- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
