---

- name: Install Docker
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - docker
    - docker-compose

- name: Ensure presence of docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add local user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes

- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
