---
- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - terminus-fonts
    - gimp
    - flac-devel
    - libvorbis-devel
    - ffmpeg-compat-devel
    - pulseaudio-libs-devel
    - libcue-devel
    - alsa-lib-devel
    - faad2-devel
    - libmad-devel
    - fontconfig-devel
    - libX11-devel
    - libXft-devel
    - ffmpeg
    - powertop
    - i3
    - i3status
    - i3lock
    - feh
    - lxappearance
    - pavucontrol
    - xbacklight
    - scrot

- service: name="gdm" enabled="no"
  become: true

- dnf: name="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" state="present"
  become: true

- command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
- command: gsettings set org.gnome.desktop.interface clock-show-date true
- command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
- command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

- file: path="{{home}}/src" state="directory"
- git: repo="https://git.blackieops.com/alexblackie/st" update="yes" dest="{{home}}/src/st"
- shell: make && make install
  args:
    chdir: "{{home}}/src/st"
    creates: /usr/local/bin/st
  become: true

- git: repo="https://github.com/cmus/cmus.git" update="yes" dest="{{home}}/src/cmus"
- shell: ./configure CONFIG_MAD=y CONFIG_OPUS=n CONFIG_ROAR=n CONFIG_JACK=n && make && make install
  args:
    chdir: "{{home}}/src/cmus"
    creates: /usr/local/bin/cmus
  become: true
