---
- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - terminus-fonts
    - gnome-tweak-tool
    - gimp

- dnf: name="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" state="present"
  become: true

- command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
- command: gsettings set org.gnome.desktop.interface clock-show-date true
