---
- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - terminus-fonts
    - gnome-tweak-tool
    - gimp
    - gstreamer-plugins-good
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-ugly
    - gstreamer1-plugins-ugly
    - ffmpeg
    - powertop

- template: src="lollypop.repo.j2" dest="/etc/yum.repos.d/lollypop.repo"
  become: true
- dnf: name="lollypop" state="present"
  become: true

- dnf: name="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" state="present"
  become: true

- command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
- command: gsettings set org.gnome.desktop.interface clock-show-date true
- command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
- command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
