---
# dnf list gnome-\* | awk '{print $1}' | sed -r 's/^(.*)\.x86_64|\.i686|\.noarch$/\1/' | grep -e '^gnome-'
- dnf: name="{{item}}" state="absent"
  become: true
  with_items:
    - gnome-abrt
    - gnome-backgrounds
    - gnome-bluetooth
    - gnome-bluetooth-libs
    - gnome-boxes
    - gnome-calculator
    - gnome-characters
    - gnome-classic-session
    - gnome-clocks
    - gnome-color-manager
    - gnome-contacts
    - gnome-desktop3
    - gnome-disk-utility
    - gnome-documents
    - gnome-documents-libs
    - gnome-font-viewer
    - gnome-getting-started-docs
    - gnome-initial-setup
    - gnome-keyring
    - gnome-keyring-pam
    - gnome-logs
    - gnome-maps
    - gnome-menus
    - gnome-online-accounts
    - gnome-online-miners
    - gnome-screenshot
    - gnome-session
    - gnome-session-wayland-session
    - gnome-session-xsession
    - gnome-settings-daemon
    - gnome-shell
    - gnome-shell-extension-alternate-tab
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-common
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-window-list
    - gnome-software
    - gnome-sound-recorder
    - gnome-system-monitor
    - gnome-terminal
    - gnome-themes-standard
    - gnome-tweak-tool
    - gnome-user-docs
    - gnome-user-share
    - gnome-video-effects
    - gnome-weather
    - gnome-2048
    - gnome-activity-journal
    - gnome-battery-bench
    - gnome-bluetooth
    - gnome-bluetooth-libs
    - gnome-bluetooth-libs-devel
    - gnome-bluetooth-libs-devel
    - gnome-books
    - gnome-builder
    - gnome-builder
    - gnome-builder-devel
    - gnome-builder-devel
    - gnome-calendar
    - gnome-chemistry-utils
    - gnome-chemistry-utils-gnumeric
    - gnome-chemistry-utils-libs
    - gnome-chemistry-utils-libs
    - gnome-chemistry-utils-mozplugin
    - gnome-chess
    - gnome-code-assistance
    - gnome-color-manager
    - gnome-colors-icon-theme
    - gnome-commander
    - gnome-commander
    - gnome-common
    - gnome-desktop
    - gnome-desktop
    - gnome-desktop-devel
    - gnome-desktop-devel
    - gnome-desktop-sharp
    - gnome-desktop-sharp-devel
    - gnome-desktop-sharp-devel
    - gnome-desktop-testing
    - gnome-desktop3
    - gnome-desktop3-devel
    - gnome-desktop3-devel
    - gnome-desktop3-tests
    - gnome-devel-docs
    - gnome-dictionary
    - gnome-dictionary
    - gnome-dictionary-devel
    - gnome-dictionary-devel
    - gnome-dictionary-libs
    - gnome-dictionary-libs
    - gnome-directory-thumbnailer
    - gnome-do
    - gnome-do-devel
    - gnome-do-devel
    - gnome-doc-utils
    - gnome-doc-utils-stylesheets
    - gnome-dvb-daemon
    - gnome-epub-thumbnailer
    - gnome-genius
    - gnome-getting-started-docs-cs
    - gnome-getting-started-docs-de
    - gnome-getting-started-docs-es
    - gnome-getting-started-docs-fr
    - gnome-getting-started-docs-gl
    - gnome-getting-started-docs-hu
    - gnome-getting-started-docs-it
    - gnome-getting-started-docs-pl
    - gnome-getting-started-docs-pt_BR
    - gnome-getting-started-docs-ru
    - gnome-gmail
    - gnome-guitar
    - gnome-guitar-devel
    - gnome-guitar-devel
    - gnome-hearts
    - gnome-icon-theme
    - gnome-icon-theme-devel
    - gnome-icon-theme-extras
    - gnome-icon-theme-legacy
    - gnome-icon-theme-symbolic
    - gnome-js-common
    - gnome-js-common-devel
    - gnome-keyring
    - gnome-keyring-pam
    - gnome-keyring-sharp
    - gnome-keyring-sharp-devel
    - gnome-keyring-sharp-devel
    - gnome-keyring-sharp-doc
    - gnome-klotski
    - gnome-kra-ora-thumbnailer
    - gnome-libs
    - gnome-libs
    - gnome-libs-devel
    - gnome-libs-devel
    - gnome-mahjongg
    - gnome-maps
    - gnome-menus
    - gnome-menus-devel
    - gnome-menus-devel
    - gnome-mime-data
    - gnome-mines
    - gnome-mud
    - gnome-multi-writer
    - gnome-music
    - gnome-nds-thumbnailer
    - gnome-nettool
    - gnome-nibbles
    - gnome-online-accounts
    - gnome-online-accounts-devel
    - gnome-online-accounts-devel
    - gnome-packagekit
    - gnome-packagekit-installer
    - gnome-packagekit-updater
    - gnome-password-generator
    - gnome-phone-manager
    - gnome-phone-manager-telepathy
    - gnome-photos
    - gnome-photos-tests
    - gnome-pie
    - gnome-pkg-tools
    - gnome-power-manager
    - gnome-python2
    - gnome-python2
    - gnome-python2-bonobo
    - gnome-python2-canvas
    - gnome-python2-desktop
    - gnome-python2-devel
    - gnome-python2-devel
    - gnome-python2-extras
    - gnome-python2-gconf
    - gnome-python2-gnome
    - gnome-python2-gnomedesktop
    - gnome-python2-gnomekeyring
    - gnome-python2-gnomevfs
    - gnome-python2-gtkspell
    - gnome-python2-libegg
    - gnome-python2-libgtop2
    - gnome-python2-libwnck
    - gnome-python2-rsvg
    - gnome-python2-totem
    - gnome-rdp
    - gnome-robots
    - gnome-screensaver
    - gnome-screensaver-frogs
    - gnome-search-tool
    - gnome-settings-daemon
    - gnome-settings-daemon-devel
    - gnome-settings-daemon-devel
    - gnome-sharp
    - gnome-sharp-devel
    - gnome-sharp-devel
    - gnome-shell-extension-auto-move-windows
    - gnome-shell-extension-calc
    - gnome-shell-extension-drive-menu
    - gnome-shell-extension-fedmsg
    - gnome-shell-extension-gpaste
    - gnome-shell-extension-iok
    - gnome-shell-extension-native-window-placement
    - gnome-shell-extension-openweather
    - gnome-shell-extension-panel-osd
    - gnome-shell-extension-pidgin
    - gnome-shell-extension-pomodoro
    - gnome-shell-extension-pomodoro
    - gnome-shell-extension-remove-bluetooth-icon
    - gnome-shell-extension-remove-volume-icon
    - gnome-shell-extension-screenshot-window-sizer
    - gnome-shell-extension-simple-dock
    - gnome-shell-extension-sustmi-historymanager-prefix-search
    - gnome-shell-extension-sustmi-windowoverlay-icons
    - gnome-shell-extension-windowsNavigator
    - gnome-shell-extension-workspace-indicator
    - gnome-shell-theme-selene
    - gnome-subtitles
    - gnome-sudoku
    - gnome-system-log
    - gnome-taquin
    - gnome-terminal-nautilus
    - gnome-tetravex
    - gnome-themes
    - gnome-themes-legacy
    - gnome-todo
    - gnome-todo-devel
    - gnome-todo-devel
    - gnome-translate
    - gnome-transliteration
    - gnome-valgrind-session
    - gnome-vfs2
    - gnome-vfs2
    - gnome-vfs2-common
    - gnome-vfs2-devel
    - gnome-vfs2-devel
    - gnome-vfs2-monikers
    - gnome-vfs2-smb
    - gnome-video-arcade
    - gnome-weather-tests
    - gnome-web-photo

- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - terminus-fonts
    - gimp
    - flac-devel
    - libvorbis-devel
    - ffmpeg-compat-devel
    - pulseaudio-libs-devel
    - libcue-devel
    - alsa-lib-devel
    - faad2-devel
    - libmad-devel
    - fontconfig-devel
    - libX11-devel
    - libXft-devel
    - ffmpeg
    - powertop
    - i3
    - i3status
    - i3lock
    - feh
    - lxappearance
    - pavucontrol
    - xbacklight
    - scrot

- service: name="gdm" enabled="no"
  become: true

- dnf: name="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" state="present"
  become: true

- command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
- command: gsettings set org.gnome.desktop.interface clock-show-date true
- command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
- command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

- file: path="{{home}}/src" state="directory"
- git: repo="https://git.blackieops.com/alexblackie/st" update="yes" dest="{{home}}/src/st"
- shell: make && make install
  args:
    chdir: "{{home}}/src/st"
    creates: /usr/local/bin/st
  become: true

- git: repo="https://github.com/cmus/cmus.git" update="yes" dest="{{home}}/src/cmus"
- shell: ./configure CONFIG_MAD=y CONFIG_OPUS=n CONFIG_ROAR=n CONFIG_JACK=n && make && make install
  args:
    chdir: "{{home}}/src/cmus"
    creates: /usr/local/bin/cmus
  become: true
