---
- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - terminus-fonts
    - gnome-tweak-tool
    - gimp

- dnf: name="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" state="present"
  become: true
