---
- name: "temp directory for storing source code archives of compiled warez"
  file: path="{{home}}/src" state="directory"

- dnf: name="{{item}}" state="latest"
  become: true
  with_items:
    - git
    - tmux
    - vim
    - zsh
    - the_silver_searcher
    - "@C Development Tools and Libraries"
    - pass
    - optipng
    - htop
    - java-1.8.0-openjdk
    - python-pygments
    - nmap
    - postgresql
    - ImageMagick
    - perf

- pip: name="awscli" state="present"
  become: true

- shell: curl -Ls https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-126.0.0-linux-x86_64.tar.gz | tar xz && \
    mv ./google-cloud-sdk ~/bin/gcloudsdk
  args:
    chdir: "{{home}}/src"
    creates: "{{home}}/bin/gcloudsdk"

- file: path="{{home}}/.env" state="touch"
- lineinfile: line="export PATH=$HOME/bin/gcloudsdk/bin:$PATH" dest="{{home}}/.env"

- user: name="{{user}}" shell="/bin/zsh"
  become: true

- git: repo="https://github.com/jhawthorn/fzy.git" dest="{{home}}/src/fzy"
- shell: "make && make install"
  become: true
  args:
    chdir: "{{home}}/src/fzy"

- name: "disable gross vim defaults"
  copy: dest="/etc/vimrc" content=""
  become: true
