---
- hosts: localhost
  tasks:

    # -------------------------------------------------------------------------
    # External playbooks
    # -------------------------------------------------------------------------

    - include: development/postgresql.yml
    - include: development/ruby.yml
    - include: development/erlang.yml
    - include: development/fedora-overrides.yml


    # -------------------------------------------------------------------------
    # Inline setup
    # -------------------------------------------------------------------------

    - name: "temp directory for storing source code archives of compiled warez"
      file:
        path: "{{home}}/src"
        state: directory

    - name: "local bin directory"
      file:
        path: "{{home}}/bin"
        state: directory

    - dnf:
        name: "{{item}}"
        state: latest
      become: true
      with_items:
        - git
        - tmux
        - vim
        - the_silver_searcher
        - "@C Development Tools and Libraries"
        - pass
        - optipng
        - htop
        - java-1.8.0-openjdk
        - nmap
        - ImageMagick
        - perf
        - dstat
        - redhat-rpm-config
        - rpm-build

    - pip:
        name: "{{item}}"
        state: present
      become: true
      with_items:
        - awscli
        - httpstat

    - shell: curl -Ls https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz | tar xzC {{home}}/bin
      args:
        creates: "{{home}}/bin/heroku"

    - file:
        path: "{{home}}/.env"
        state: touch
    - lineinfile:
        line: export PATH=$HOME/bin/heroku/bin:$PATH
        dest: "{{home}}/.env"

    - git:
        repo: https://github.com/jhawthorn/fzy.git
        dest: "{{home}}/src/fzy"
    - shell: "make && make install"
      become: true
      args:
        chdir: "{{home}}/src/fzy"
