---
- hosts: localhost
  tasks:

    # -------------------------------------------------------------------------
    # General config
    # -------------------------------------------------------------------------

    - include: shared_tasks/development.yml

    - name: "disable gross vim defaults"
      copy:
        dest: /etc/vimrc
        content: ""
      become: true

    - name: "disable stupid ls colors"
      copy:
        dest: /etc/profile.d/colorls.sh
        content: ""
      become: true

    - dnf:
        name: "{{item}}"
        state: latest
      become: true
      with_items:
        - git
        - tmux
        - vim
        - the_silver_searcher
        - "@C Development Tools and Libraries"
        - pass
        - optipng
        - htop
        - java-1.8.0-openjdk
        - nmap
        - ImageMagick
        - perf
        - dstat
        - redhat-rpm-config
        - rpm-build


    # -------------------------------------------------------------------------
    # Erlang
    # -------------------------------------------------------------------------

    - name: "Install Erlang"
      dnf:
        name: erlang
        state: latest
      become: true


    # -------------------------------------------------------------------------
    # PostgreSQL
    # -------------------------------------------------------------------------

    - name: "Install postgresql server and client libs"
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-psycopg2
        - postgresql
        - postgresql-devel
        - postgresql-server
        - postgresql-contrib
      become: true

    - name: "Initialize PostgreSQL data directory"
      command: "postgresql-setup --initdb --unit postgresql"
      args:
        creates: /var/lib/pgsql/data/pg_hba.conf
      become: true

    - name: "Enable and start postresql"
      service:
        name: postgresql
        enabled: yes
        state: started
      become: true

    - name: "Add superuser role for default user"
      postgresql_user:
        name: "{{ user }}"
        role_attr_flags: SUPERUSER,LOGIN
        state: present
      become: true
      become_user: postgres


    # -------------------------------------------------------------------------
    # Redis
    # -------------------------------------------------------------------------
    - name: "Install redis"
      dnf:
        name: redis
        state: present
      become: true

    - name: "Enable and start redis"
      service:
        name: redis
        state: started
        enabled: yes
      become: true


    # -------------------------------------------------------------------------
    # Ruby
    # -------------------------------------------------------------------------

    - name: "Add chruby and ruby-install copr repos"
      command: dnf copr enable -y postmodern/{{ item }}
      become: true
      args:
        creates: /etc/yum.repos.d/_copr_postmodern-{{ item }}.repo
      with_items:
        - ruby-install
        - chruby

    - name: "Install chruby and ruby-install"
      dnf:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - ruby-install
        - chruby

    - include: shared_tasks/rubbies.yml


    # -------------------------------------------------------------------------
    # Python
    # -------------------------------------------------------------------------

    - name: "Install python and some libs"
      dnf:
        name: "{{ item }}"
      with_items:
        - python3-devel
        - python2-virtualenv
        - python-pygments
