---
- hosts: localhost
  tasks:
    - dnf:
        name: "{{item}}"
        state: present
      become: true
      with_items:
        - docker
        - docker-compose

    - include: shared_tasks/docker.yml
